- job_name: 'power'
  scrape_timeout: 5m
  scrape_interval: 5m
  static_configs:
    - targets:
        - localhost:9106
  # Remove port from hostname label
  relabel_configs:
    - source_labels: [__address__]
      target_label: instance
      regex: '([^:]+)(:[0-9]+)?'
      replacement: '${1}'
