  - job_name: 'slurm-job'
    scrape_interval: 5m
    file_sd_configs:
      - files:
        - '/etc/victoria-metrics/targets/slurm-job-exporter.yml'
    # Remove port from hostname label
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
